package com.enovka.gemini4j.domain;

import com.enovka.gemini4j.domain.type.AnswerStyleEnum;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the desired style for grounded answers generated by the Gemini
 * API. This allows you to control the level of detail and conciseness in the
 * responses.
 *
 * @author Everson Novka &lt;enovka@gmail.com&gt;
 */
@Data
@Builder(setterPrefix = "with", toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class AnswerStyle {

    /**
     * The specific answer style from the {@link AnswerStyleEnum}. For example,
     * setting this to {@link AnswerStyleEnum#ABSTRACTIVE} requests a succinct
     * and abstract answer style.
     */
    @JsonProperty("answerStyle")
    private AnswerStyleEnum answerStyle;
}