package com.enovka.gemini4j.domain;

import com.enovka.gemini4j.domain.type.HarmProbabilityEnum;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the probability that a piece of content generated by the Gemini
 * API is harmful according to the API's safety classification system. This
 * class provides a structured way to access the harm probability assessment,
 * allowing developers to evaluate the safety level of the generated content.
 * Note that this probability only indicates the likelihood of harm and does not
 * reflect the severity of the potential harm.
 *
 * @author Everson Novka <enovka@gmail.com>
 */
@Data
@Builder(setterPrefix = "with")
@NoArgsConstructor
@AllArgsConstructor
public class HarmProbability {

    /**
     * The specific harm probability level, as determined by the Gemini API's
     * safety classification system, represented by the
     * {@link HarmProbabilityEnum}. For example, a value of
     * {@link HarmProbabilityEnum#HIGH} indicates a high probability of harm.
     */
    @JsonProperty("harmProbability")
    private HarmProbabilityEnum harmProbability;
}