package com.enovka.gemini4j.domain;

import com.enovka.gemini4j.domain.type.HarmProbabilityEnum;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the probability that a piece of content generated by the Gemini
 * API is harmful according to the API's safety classification system. This
 * class provides a structured way to access the harm probability assessment,
 * allowing developers to evaluate the safety level of the generated content.
 * Note that this probability only indicates the likelihood of harm and does not
 * reflect the severity of the potential harm.
 *
 * @author Everson Novka &lt;enovka@gmail.com&gt;
 */
@Data
@Builder(setterPrefix = "with", toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class HarmProbability {

    /**
     * The specific harm probability level, as determined by the Gemini API's
     * safety classification system, represented by the
     * {@link HarmProbabilityEnum}. For example, a value of
     * {@link HarmProbabilityEnum#HIGH} indicates a high probability of harm.
     */
    @JsonProperty("probability")
    private String probability; // Define como string

    /**
     * Creates a `HarmProbability` instance from a JSON string representing the
     * harm probability.
     *
     * @param probability The JSON string representing the harm probability.
     * @return A `HarmProbability` instance with the harm probability set from
     * the JSON string.
     */
    public static HarmProbability fromJsonString(String probability) {
        return HarmProbability.builder()
                .withProbability(probability) // Define como string
                .build();
    }

    /**
     * Returns the `HarmProbabilityEnum` corresponding to the `probability`
     * string.
     *
     * @return The `HarmProbabilityEnum` value.
     */
    public HarmProbabilityEnum getHarmProbabilityEnum() {
        return HarmProbabilityEnum.valueOf(probability);
    }
}