name: Java CI with Maven, WireMock, Javadoc and Website Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POM_FILE: pom.xml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Start WireMock
        run: java -jar wiremock-standalone-3.8.0.jar --port 8080 &
      - name: Build with Maven
        run: mvn -B package --file ${{ env.POM_FILE }}
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Deploy Javadoc to GitHub Pages
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          java-version: '11'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages
          target-folder: javadocs
          javadoc-source-folder: target/site/apidocs
      - name: Deploy website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs