name: Build and Test with WireMock

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Maven
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Maven
        run: npm install -g maven
      - name: Grant execute permission for mvn
        run: chmod +x mvn
      - name: Start WireMock
        uses: cjayanth95/setup-wiremock-action@v0.2.0
      - name: Build and Test
        run: mvn clean install -Dwiremock.host=localhost
