name: Java CI with Maven and Javadoc Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy Javadoc to GitHub Pages
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          java-version: '11'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          target-folder: .
          javadoc-source-folder: target/site/apidocs